### ISSUE TITLE
Use CMake FetchContent?

### ISSUE THREAD

**Issue by ArthurSonzogni** [adrianoviana87/ltuiny#2]
Hi adrianoviana87.

That's a really nice repository! I love the UI you made!
I will add a link to your repository into the FTXUI one.
___________

I notice you wrote in your README:
> FTXUI -- I have to include this dependency as a submodule or something like that. For now, you can download the FTXUI repository and install the library.

If you don't want to require users of your library to download your dependencies themselves, I would like to let you know you could use CMake [FetchContent](https://cmake.org/cmake/help/v3.11/module/FetchContent.html).

CMake will download the repository for you at build time.

I have made an example with FTXUI:
https://github.com/ArthurSonzogni/ftxui-starter/blob/master/CMakeLists.txt

You would just need to include this fragment of code:
```ocaml
include(FetchContent)

set(FETCHCONTENT_UPDATES_DISCONNECTED TRUE)
FetchContent_Declare(ftxui
  GIT_REPOSITORY https://github.com/ArthurSonzogni/ftxui
  # Specify a GIT TAG here.
)

FetchContent_GetProperties(ftxui)
if(NOT ftxui_POPULATED)
  FetchContent_Populate(ftxui)
  add_subdirectory(${ftxui_SOURCE_DIR} ${ftxui_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()
```
The only drawbacks is that it requires cmake 3.11

**Comment by adrianoviana87** [comment]
@ArthurSonzogni  thank you. Your library is amazing!
I'm glad you like it. I'll use your example since it's a good thing not to have to install your library separately in order to build the app.

**Comment by ArthurSonzogni** [comment]
Thanks for your review!
